"use client";
import {useMemo,useState} from "react";
import {money} from "@/lib/storage";
import {researchLinks} from "@/lib/research";
import {MarketSource} from "@/lib/types";

type AutoResult={market:number|null;low:number|null;high:number|null;setName?:string;summary?:string;sources:MarketSource[];methodology?:string};
export default function Research(){
 const [setNumber,setSetNumber]=useState(""),[condition,setCondition]=useState<"N"|"U">("N"),[result,setResult]=useState<AutoResult|null>(null),[loading,setLoading]=useState(false),[note,setNote]=useState("");
 const links=useMemo(()=>setNumber?researchLinks(setNumber):[],[setNumber]);
 async function lookup(){if(!setNumber)return;setLoading(true);setResult(null);setNote("Searching current public web prices…");try{const r=await fetch(`/api/market-value?setNumber=${encodeURIComponent(setNumber)}&condition=${condition}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Research failed");setResult(d);setNote(d.sources?.length?`Found ${d.sources.length} usable price sources.${d.summary?` ${d.summary}`:""}`:"The search completed but could not verify enough numeric prices. Use the fallback links below.")}catch(e){setNote(e instanceof Error?e.message:"Research failed")}finally{setLoading(false)}}
 return <><div className="header"><div><div className="eyebrow">Automatic set-by-set market research</div><h1>Price Research</h1><div className="muted">One set number → live web research → source-by-source market estimate.</div></div></div><section className="card"><div className="research-search"><input className="input" placeholder="Set number, e.g. 75313" value={setNumber} onChange={e=>setSetNumber(e.target.value)}/><select value={condition} onChange={e=>setCondition(e.target.value as "N"|"U")}><option value="N">New / sealed</option><option value="U">Used complete</option></select><button className="btn accent" onClick={lookup} disabled={!setNumber||loading}>{loading?"Researching the web…":"Research automatically"}</button></div>{note&&<div className="notice" style={{marginTop:12}}>{note}</div>}</section>{result&&<section className="card" style={{marginTop:16}}><div className="section-title"><div><h2>{result.setName||`LEGO ${setNumber}`}</h2><span className="muted">Automatic market estimate</span></div><strong className="hero-price">{result.market?money(result.market):"No verified estimate"}</strong></div>{result.market&&<div className="muted" style={{marginBottom:12}}>Observed source range: {money(result.low||result.market)} – {money(result.high||result.market)}</div>}<div className="source-grid">{(result.sources||[]).map((s,idx)=><a className="source-card clickable" href={s.url||"#"} target="_blank" rel="noreferrer" key={`${s.source}-${idx}`}><b>{s.label}</b><strong>{money(s.value)}</strong><small>{s.detail||s.kind}</small></a>)}</div>{result.methodology&&<div className="notice" style={{marginTop:14}}>{result.methodology}</div>}</section>}{setNumber&&<section className="card" style={{marginTop:16}}><div className="section-title"><h2>Fallback public pages</h2><span className="muted">Only needed when automatic search cannot verify a value</span></div><div className="source-links">{links.map(l=><a key={l.source} className={`source-link ${l.tier}`} href={l.url} target="_blank" rel="noreferrer"><div><b>{l.label}</b><small>{l.purpose}</small></div><span>↗</span></a>)}</div></section>}</>;
}
