const $ = (sel, root=document) => root.querySelector(sel);
const $$ = (sel, root=document) => [...root.querySelectorAll(sel)];
const money = n => Number(n||0).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
const pct = n => `${Number(n)>=0?'+':''}${Number(n||0).toFixed(1)}%`;
const uid = () => (crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`);
const today = () => new Date().toISOString().slice(0,10);
const STORAGE='lego-investment-hub-v4';
const WATCH='lego-investment-watch-v4';
const seed=[
 {id:uid(),setNumber:'75342-1',name:'Republic Fighter Tank',condition:'new',quantity:28,cost:45,marketValue:58,storePrice:65,status:'For Sale',location:'',notes:'',imageUrl:'',theme:'Star Wars',priceHistory:[{date:'2026-07-15',value:54},{date:'2026-08-01',value:56},{date:today(),value:58}]},
 {id:uid(),setNumber:'75331-1',name:'The Razor Crest',condition:'new',quantity:1,cost:700,marketValue:760,storePrice:800,status:'For Sale',location:'',notes:'',imageUrl:'',theme:'Star Wars',priceHistory:[{date:'2026-07-15',value:720},{date:'2026-08-01',value:742},{date:today(),value:760}]},
 {id:uid(),setNumber:'75314-1',name:'The Bad Batch Attack Shuttle',condition:'new',quantity:1,cost:90,marketValue:240,storePrice:250,status:'For Sale',location:'',notes:'',imageUrl:'',theme:'Star Wars',priceHistory:[{date:'2026-07-15',value:215},{date:'2026-08-01',value:229},{date:today(),value:240}]}
];
let state={tab:'dashboard',items:load(STORAGE,seed),watch:load(WATCH,[]),query:'',editing:null,busy:null,news:[],apiStatus:null};
function load(k,fallback){try{const x=JSON.parse(localStorage.getItem(k));return Array.isArray(x)?x:fallback}catch{return fallback}}
function persist(){localStorage.setItem(STORAGE,JSON.stringify(state.items));localStorage.setItem(WATCH,JSON.stringify(state.watch))}
function normalizeSet(v){const s=String(v||'').trim();return s.includes('-')?s:`${s}-1`}
function itemChange(item,days){const h=[...(item.priceHistory||[])].sort((a,b)=>a.date.localeCompare(b.date));if(!h.length||!item.marketValue)return 0;const target=Date.now()-days*864e5;let near=h[0];for(const p of h){if(Math.abs(Date.parse(p.date)-target)<Math.abs(Date.parse(near.date)-target))near=p}return near.value?((item.marketValue-near.value)/near.value)*100:0}
function portfolioHistory(items){const dates=[...new Set(items.flatMap(i=>(i.priceHistory||[]).map(p=>p.date)))].sort();return dates.map(date=>({date,value:items.reduce((sum,i)=>{let val=i.marketValue||0;const hist=[...(i.priceHistory||[])].sort((a,b)=>a.date.localeCompare(b.date));for(const p of hist){if(p.date<=date)val=p.value}return sum+val*(i.quantity||0)},0)}))}
function portfolioChange(hist,days,current){if(!hist.length||!current)return 0;const target=Date.now()-days*864e5;let near=hist[0];for(const p of hist){if(Math.abs(Date.parse(p.date)-target)<Math.abs(Date.parse(near.date)-target))near=p}return near.value?((current-near.value)/near.value)*100:0}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function nav(){return `<div class="topbar"><div class="topbar-inner"><div class="brand"><span class="brick"></span>LEGO Investment Hub</div><div class="nav">${['dashboard','inventory','market','news','watchlist','status'].map(t=>`<button data-tab="${t}" class="${state.tab===t?'active':''}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div><div class="spacer"></div><div class="muted status-label"><span class="status-dot ${state.apiStatus?.bricklink?'ok':''}"></span>Market APIs</div></div></div>`}
function hero(kicker,title,sub=''){return `<div class="hero"><div class="eyebrow">${esc(kicker)}</div><h1>${esc(title)}</h1>${sub?`<div class="sub">${esc(sub)}</div>`:''}</div>`}
function dashboard(){const items=state.items,cost=items.reduce((s,i)=>s+(i.cost||0)*(i.quantity||0),0),market=items.reduce((s,i)=>s+(i.marketValue||0)*(i.quantity||0),0),retail=items.reduce((s,i)=>s+(i.storePrice||0)*(i.quantity||0),0),roi=cost?((market-cost)/cost)*100:0,h=portfolioHistory(items),c30=portfolioChange(h,30,market),unique=items.length,units=items.reduce((s,i)=>s+(i.quantity||0),0);return `${hero('LEGO inventory intelligence','Your collection, priced like a portfolio.','Track cost, live market value, store pricing, performance, watchlist opportunities and LEGO investment news in one place.')}<div class="grid metrics"><div class="card metric"><div class="label">Market value</div><div class="value">${money(market)}</div></div><div class="card metric"><div class="label">Cost basis</div><div class="value">${money(cost)}</div></div><div class="card metric"><div class="label">Unrealized return</div><div class="value ${roi>=0?'positive':'negative'}">${pct(roi)}</div></div><div class="card metric"><div class="label">30-day portfolio trend</div><div class="value ${c30>=0?'positive':'negative'}">${pct(c30)}</div></div></div><div class="grid two section"><div class="card"><div class="section-head"><h2>Portfolio history</h2><span class="muted">Updates as market prices are refreshed</span></div>${bars(h.map(x=>x.value))}</div><div class="card"><h2 style="margin-top:0">Portfolio snapshot</h2><div class="kpi-row"><div class="kpi"><span class="muted">Unique sets</span><b>${unique}</b></div><div class="kpi"><span class="muted">Total units</span><b>${units}</b></div><div class="kpi"><span class="muted">Potential retail</span><b>${money(retail)}</b></div></div><p class="muted">Automated market estimates never overwrite your cost or your store price.</p></div></div>${inventorySection(state.items.slice(0,8),true)}`}
function bars(data){if(!data.length)return '<div class="empty">Refresh prices to build portfolio history.</div>';const max=Math.max(...data,1),min=Math.min(...data,0);return `<div class="chart">${data.map(v=>`<div class="bar" title="${money(v)}" style="height:${Math.max(7,((v-min)/(max-min||1))*100)}%"></div>`).join('')}</div>`}
function filtered(){const q=state.query.trim().toLowerCase();return state.items.filter(i=>`${i.name} ${i.setNumber} ${i.theme||''} ${i.status||''}`.toLowerCase().includes(q))}
function inventory(){return `${hero('Inventory','Every set, one clean record.','Add sets by number, edit what you paid, set your own store price, track quantity and refresh current market value whenever you want.')}${inventorySection(filtered(),false)}`}
function inventorySection(items,compact){return `<div class="section"><div class="section-head"><h2>${compact?'Inventory overview':'Inventory'}</h2><div class="toolbar">${compact?'':`<input id="search" class="input search" placeholder="Search set, number, theme…" value="${esc(state.query)}">`}<button class="btn" data-action="add">+ Add set</button></div></div><div class="table-wrap"><table><thead><tr><th>Set</th><th>Condition</th><th>Qty</th><th>Your cost</th><th>Market</th><th>Store price</th><th>30d</th><th>ROI</th><th></th></tr></thead><tbody>${items.map(row).join('')||`<tr><td colspan="9"><div class="empty">No sets found.</div></td></tr>`}</tbody></table></div></div>`}
function row(i){const roi=i.cost?((i.marketValue-i.cost)/i.cost)*100:0,c30=itemChange(i,30);return `<tr><td><div class="setcell">${i.imageUrl?`<img class="thumb" src="${esc(i.imageUrl)}" alt="">`:'<div class="thumb"></div>'}<div><b>${esc(i.name||'Unnamed set')}</b><div class="muted">#${esc(i.setNumber)}</div></div></div></td><td><span class="pill">${i.condition==='new'?'New / sealed':'Used complete'}</span></td><td>${Number(i.quantity||0)}</td><td>${money(i.cost)}</td><td><b>${money(i.marketValue)}</b></td><td>${money(i.storePrice)}</td><td class="${c30>=0?'positive':'negative'}">${pct(c30)}</td><td class="${roi>=0?'positive':'negative'}">${pct(roi)}</td><td><div class="toolbar"><button class="btn ghost" data-price="${i.id}" ${state.busy===i.id?'disabled':''}>${state.busy===i.id?'Checking…':'Find price'}</button><button class="btn secondary" data-edit="${i.id}">Edit</button></div></td></tr>`}
function market(){return `${hero('Market intelligence','Source-by-source market estimates.','BrickLink completed sales are weighted highest. BrickEconomy valuations and active BrickLink/eBay listings provide additional signals, with outliers automatically discounted.')}<div class="notice section">Market value is separate from your cost and your store price. A refresh only changes the market estimate and adds a dated price snapshot.</div><div class="grid market-grid section">${state.items.map(i=>marketCard(i)).join('')||'<div class="empty">Add inventory to start pricing.</div>'}</div>`}
function marketCard(i){const q=i.lastQuote;return `<div class="card market-card"><div class="section-head"><div><b>${esc(i.name||'Unnamed set')}</b><div class="muted">#${esc(i.setNumber)} · ${i.condition==='new'?'New / sealed':'Used complete'}</div></div><button class="btn" data-price="${i.id}" ${state.busy===i.id?'disabled':''}>${state.busy===i.id?'Checking…':'Refresh'}</button></div><div class="price">${money(i.marketValue)}</div>${q?`<div>${(q.sources||[]).map(s=>`<div class="source"><span><b>${esc(s.label||s.source)}</b><small class="muted" style="display:block">${esc(s.note||'')}</small></span><b>${money(s.value)}</b></div>`).join('')}</div><div class="muted" style="margin-top:8px">Confidence: ${esc(q.confidence||'—')} · ${q.sourceCount||0} source${q.sourceCount===1?'':'s'} used</div>${q.warnings?.length?`<details style="margin-top:8px"><summary class="muted">Unavailable sources (${q.warnings.length})</summary><div class="muted">${q.warnings.map(esc).join(' · ')}</div></details>`:''}`:'<div class="muted">No live quote fetched yet.</div>'}</div>`}
function news(){return `${hero('LEGO investment news','Useful LEGO market information, condensed.','Refresh a broad LEGO investment news search and scan retirement, resale, pricing and collector-market stories without opening dozens of sites.')}<div class="section-head section"><h2>Latest market news</h2><button class="btn" data-action="news">Refresh news</button></div>${state.news.length?`<div class="grid news-grid">${state.news.map(n=>`<article class="card news-card"><span class="tag">${esc(n.source||'News')}</span><h3><a href="${esc(n.link)}" target="_blank" rel="noopener">${esc(n.title)}</a></h3><div class="muted">${esc(n.date||'')}</div>${n.summary?`<p>${esc(n.summary)}</p>`:''}</article>`).join('')}</div>`:'<div class="card empty">Click “Refresh news” to load current LEGO investment, retirement and resale-market stories.</div>'}`}
function watchlist(){return `${hero('Watchlist','Track sets before you buy.','Keep possible investments separate from your owned inventory, record a target buy price, and pull live market pricing before making a purchase.')}<div class="section-head section"><h2>Watchlist</h2><button class="btn" data-watchadd="1">+ Add watch item</button></div><div class="grid market-grid">${state.watch.map(w=>`<div class="card"><div class="section-head"><div><b>${esc(w.name||'Watch item')}</b><div class="muted">#${esc(w.setNumber)}</div></div><button class="btn danger" data-watchdel="${w.id}">Remove</button></div><div class="kpi-row"><div class="kpi"><span class="muted">Target buy</span><b>${money(w.target)}</b></div><div class="kpi"><span class="muted">Last market</span><b>${money(w.marketValue)}</b></div></div><div class="toolbar" style="margin-top:14px"><button class="btn ghost" data-watchprice="${w.id}">Check market</button><button class="btn secondary" data-watchmove="${w.id}">Move to inventory</button></div></div>`).join('')||'<div class="card empty">No watchlist items yet.</div>'}</div>`}
function status(){const s=state.apiStatus;return `${hero('Connections','Pricing and catalog API status.','API keys stay on Vercel as environment variables. They are never stored in your browser or committed to GitHub.')}<div class="card section"><div class="section-head"><h2>Provider status</h2><button class="btn" data-action="status">Recheck</button></div>${s?`<div class="api-list">${[['bricklink','BrickLink','Completed sales + current listings'],['brickeconomy','BrickEconomy','Independent new/used valuation + history'],['rebrickable','Rebrickable','Set names, images and catalog data'],['ebay','eBay','Active listing signal']].map(([k,n,d])=>`<div class="api-row"><div><b>${n}</b><div class="muted">${d}</div></div><div class="state ${s[k]?'ok':'missing'}">${s[k]?'Configured':'Needs key'}</div></div>`).join('')}</div>`:'<div class="empty">Checking API configuration…</div>'}<div class="warning" style="margin-top:16px"><b>Required for the strongest setup:</b> Rebrickable + BrickLink. BrickEconomy and eBay are optional additional signals.</div></div>`}
function editor(i){const x=i||{id:uid(),setNumber:'',name:'',condition:'new',quantity:1,cost:0,marketValue:0,storePrice:0,status:'For Sale',location:'',notes:'',imageUrl:'',theme:'',priceHistory:[]};state.editing=x;return `<div class="modal-bg"><div class="modal"><div class="section-head"><h2>${i?'Edit set':'Add set'}</h2><button class="btn secondary" data-action="close">Close</button></div><form id="editForm"><input type="hidden" name="id" value="${esc(x.id)}"><div class="formgrid"><div class="field"><label>Set number</label><div class="toolbar"><input class="grow" name="setNumber" value="${esc(x.setNumber)}" placeholder="75331"><button class="btn ghost" type="button" data-action="lookup">Find set</button></div></div><div class="field"><label>Set name</label><input name="name" value="${esc(x.name)}"></div><div class="field"><label>Condition</label><select name="condition"><option value="new" ${x.condition==='new'?'selected':''}>New / sealed</option><option value="used" ${x.condition==='used'?'selected':''}>Used complete</option></select></div><div class="field"><label>Quantity</label><input name="quantity" type="number" min="1" value="${Number(x.quantity||1)}"></div><div class="field"><label>Your cost per set</label><input name="cost" type="number" step="0.01" value="${Number(x.cost||0)}"></div><div class="field"><label>Current market value</label><input name="marketValue" type="number" step="0.01" value="${Number(x.marketValue||0)}"></div><div class="field"><label>Your store price</label><input name="storePrice" type="number" step="0.01" value="${Number(x.storePrice||0)}"></div><div class="field"><label>Status</label><select name="status">${['For Sale','Hold','Personal','Consignment'].map(v=>`<option ${x.status===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Location</label><input name="location" value="${esc(x.location||'')}"></div><div class="field"><label>Theme</label><input name="theme" value="${esc(x.theme||'')}"></div></div><div class="field" style="margin-top:13px"><label>Notes</label><textarea name="notes" rows="3">${esc(x.notes||'')}</textarea></div><div class="toolbar" style="justify-content:flex-end;margin-top:18px"><button type="button" class="btn secondary" data-action="close">Cancel</button>${i?'<button type="button" class="btn danger" data-action="delete">Delete</button>':''}<button class="btn" type="submit">Save set</button></div></form></div></div>`}
function watchEditor(){return `<div class="modal-bg"><div class="modal"><div class="section-head"><h2>Add watchlist set</h2><button class="btn secondary" data-action="close">Close</button></div><form id="watchForm"><div class="formgrid"><div class="field"><label>Set number</label><input name="setNumber" required placeholder="75331"></div><div class="field"><label>Set name</label><input name="name"></div><div class="field"><label>Condition</label><select name="condition"><option value="new">New / sealed</option><option value="used">Used complete</option></select></div><div class="field"><label>Target buy price</label><input name="target" type="number" step="0.01"></div></div><div class="toolbar" style="justify-content:flex-end;margin-top:18px"><button class="btn" type="submit">Add to watchlist</button></div></form></div></div>`}
function content(){switch(state.tab){case'inventory':return inventory();case'market':return market();case'news':return news();case'watchlist':return watchlist();case'status':return status();default:return dashboard()}}
function render(modal=''){document.querySelector('#app').innerHTML=`<div class="app">${nav()}<main class="shell">${content()}</main>${modal}</div>`;bind()}
function bind(){$$('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render();if(state.tab==='status'&&!state.apiStatus)checkStatus()});const s=$('#search');if(s)s.oninput=e=>{state.query=e.target.value;render()};$$('[data-action="add"]').forEach(b=>b.onclick=()=>render(editor(null)));$$('[data-edit]').forEach(b=>b.onclick=()=>{const i=state.items.find(x=>x.id===b.dataset.edit);render(editor(structuredClone(i)))});$$('[data-price]').forEach(b=>b.onclick=()=>refreshPrice(b.dataset.price));$$('[data-action="close"]').forEach(b=>b.onclick=()=>{state.editing=null;render()});const f=$('#editForm');if(f)f.onsubmit=saveForm;const lookup=$('[data-action="lookup"]');if(lookup)lookup.onclick=lookupSet;const del=$('[data-action="delete"]');if(del)del.onclick=deleteItem;const newsBtn=$('[data-action="news"]');if(newsBtn)newsBtn.onclick=loadNews;const statusBtn=$('[data-action="status"]');if(statusBtn)statusBtn.onclick=checkStatus;const wa=$('[data-watchadd]');if(wa)wa.onclick=()=>render(watchEditor());const wf=$('#watchForm');if(wf)wf.onsubmit=saveWatch;$$('[data-watchdel]').forEach(b=>b.onclick=()=>{state.watch=state.watch.filter(x=>x.id!==b.dataset.watchdel);persist();render()});$$('[data-watchmove]').forEach(b=>b.onclick=()=>moveWatch(b.dataset.watchmove));$$('[data-watchprice]').forEach(b=>b.onclick=()=>priceWatch(b.dataset.watchprice))}
function saveForm(e){e.preventDefault();const fd=new FormData(e.currentTarget),old=state.items.find(i=>i.id===fd.get('id'));const x={...(old||{}),id:fd.get('id'),setNumber:normalizeSet(fd.get('setNumber')),name:fd.get('name'),condition:fd.get('condition'),quantity:Number(fd.get('quantity')||1),cost:Number(fd.get('cost')||0),marketValue:Number(fd.get('marketValue')||0),storePrice:Number(fd.get('storePrice')||0),status:fd.get('status'),location:fd.get('location'),theme:fd.get('theme'),notes:fd.get('notes'),priceHistory:old?.priceHistory||[],imageUrl:old?.imageUrl||'',updatedAt:new Date().toISOString()};state.items=old?state.items.map(i=>i.id===x.id?x:i):[x,...state.items];persist();state.editing=null;render()}
async function lookupSet(){const f=$('#editForm'),num=normalizeSet(new FormData(f).get('setNumber'));if(!num)return;const btn=$('[data-action="lookup"]');btn.disabled=true;btn.textContent='Finding…';try{const r=await fetch(`/api/catalog?set=${encodeURIComponent(num)}`),j=await r.json();if(!r.ok)throw new Error(j.error||'Set not found');f.elements.setNumber.value=j.setNumber||num;f.elements.name.value=j.name||f.elements.name.value;f.elements.theme.value=j.theme||f.elements.theme.value;const old=state.items.find(i=>i.id===f.elements.id.value);if(old&&j.imageUrl)old.imageUrl=j.imageUrl;state.editing={...(state.editing||{}),imageUrl:j.imageUrl||state.editing?.imageUrl||''};}catch(e){alert(e.message)}finally{btn.disabled=false;btn.textContent='Find set'}}
function deleteItem(){if(!state.editing)return;if(confirm('Delete this set from inventory?')){state.items=state.items.filter(i=>i.id!==state.editing.id);persist();state.editing=null;render()}}
async function refreshPrice(id){const i=state.items.find(x=>x.id===id);if(!i)return;state.busy=id;render();try{const r=await fetch(`/api/market?set=${encodeURIComponent(normalizeSet(i.setNumber))}&condition=${i.condition}`),q=await r.json();if(!r.ok)throw new Error(q.error||'No live price available');if(!q.estimate)throw new Error('No configured pricing source returned a usable value. Check API Status.');state.items=state.items.map(x=>x.id===id?{...x,marketValue:q.estimate,lastQuote:q,priceHistory:[...(x.priceHistory||[]),{date:today(),value:q.estimate}],updatedAt:new Date().toISOString()}:x);persist()}catch(e){alert(e.message)}finally{state.busy=null;render()}}
async function loadNews(){const b=$('[data-action="news"]');if(b){b.disabled=true;b.textContent='Searching…'}try{const r=await fetch('/api/news'),j=await r.json();if(!r.ok)throw new Error(j.error||'News search failed');state.news=j.items||[];render()}catch(e){alert(e.message);render()}}
async function checkStatus(){try{const r=await fetch('/api/status'),j=await r.json();state.apiStatus=j;render()}catch{state.apiStatus={bricklink:false,brickeconomy:false,rebrickable:false,ebay:false};render()}}
function saveWatch(e){e.preventDefault();const fd=new FormData(e.currentTarget);state.watch.unshift({id:uid(),setNumber:normalizeSet(fd.get('setNumber')),name:fd.get('name'),condition:fd.get('condition'),target:Number(fd.get('target')||0),marketValue:0});persist();render()}
function moveWatch(id){const w=state.watch.find(x=>x.id===id);if(!w)return;state.items.unshift({id:uid(),setNumber:w.setNumber,name:w.name,condition:w.condition,quantity:1,cost:0,marketValue:w.marketValue||0,storePrice:0,status:'Hold',location:'',notes:'Moved from watchlist',theme:'',imageUrl:'',priceHistory:w.marketValue?[{date:today(),value:w.marketValue}]:[]});state.watch=state.watch.filter(x=>x.id!==id);persist();render()}
async function priceWatch(id){const w=state.watch.find(x=>x.id===id);if(!w)return;try{const r=await fetch(`/api/market?set=${encodeURIComponent(w.setNumber)}&condition=${w.condition}`),q=await r.json();if(!r.ok||!q.estimate)throw new Error(q.error||'No price available');w.marketValue=q.estimate;persist();render()}catch(e){alert(e.message)}}
render();checkStatus();
