"use client";
import {useEffect,useMemo,useState} from "react";
import {getInventory,importLocalInventoryIfNeeded,upsertInventoryItem,deleteInventoryItem,requestPriceRefresh,requestStalePriceRefresh,money} from "@/lib/storage";
import {Condition,InventoryStatus,LegoItem,MarketSource} from "@/lib/types";

const blank={setNumber:"",name:"",theme:"",condition:"New/Sealed" as Condition,quantity:1,cost:0,market:0,storePrice:0,status:"For Sale" as InventoryStatus,location:"",notes:"",imageUrl:undefined as string|undefined,year:undefined as number|undefined,marketSources:[] as MarketSource[]};
export default function Inventory(){
 const [items,setItems]=useState<LegoItem[]>([]),[q,setQ]=useState(""),[open,setOpen]=useState(false),[editing,setEditing]=useState<LegoItem|null>(null),[form,setForm]=useState(blank),[note,setNote]=useState("Connecting to Supabase…"),[busy,setBusy]=useState(false);
 async function load(){try{const r=await importLocalInventoryIfNeeded();setItems(r.items);setNote(r.imported?`Imported ${r.imported} existing browser inventory items into Supabase.`:"Supabase connected. Your inventory is stored centrally.");await requestStalePriceRefresh(24);setItems(await getInventory())}catch(e){setNote(e instanceof Error?e.message:"Could not connect to Supabase.")}}
 useEffect(()=>{void load();const h=()=>void getInventory().then(setItems);window.addEventListener("inventory-change",h);return()=>window.removeEventListener("inventory-change",h)},[]);
 const filtered=useMemo(()=>items.filter(i=>(i.name+" "+i.setNumber+" "+i.theme).toLowerCase().includes(q.toLowerCase())),[items,q]);
 const queued=items.filter(i=>i.refreshRequested).length;
 const openAdd=()=>{setEditing(null);setForm(blank);setOpen(true)};
 const openEdit=(item:LegoItem)=>{setEditing(item);setForm({...blank,...item});setOpen(true)};
 async function lookupSet(){if(!form.setNumber)return;try{const r=await fetch(`/api/rebrickable/set?setNumber=${encodeURIComponent(form.setNumber)}`);const d=await r.json();if(d.name)setForm(f=>({...f,name:d.name||f.name,imageUrl:d.set_img_url||f.imageUrl,year:d.year||f.year}))}catch{}}
 async function save(){if(!form.setNumber||!form.name){setNote("Set number and set name are required.");return}setBusy(true);try{const now=new Date().toISOString(),date=now.slice(0,10);const item:LegoItem=editing?{...editing,...form}:{...form,id:`${form.setNumber}-${Date.now()}`,history:[]};if(!item.history)item.history=[];if(!editing||form.market!==editing.market)item.history=[...(item.history||[]).filter(h=>h.date!==date),{date,market:Number(form.market)}];await upsertInventoryItem(item);setItems(await getInventory());setOpen(false);setNote("Saved to Supabase.")}catch(e){setNote(e instanceof Error?e.message:"Save failed.")}finally{setBusy(false)}}
 async function remove(id:string){if(!confirm("Delete this set from inventory?"))return;await deleteInventoryItem(id);setItems(await getInventory())}
 async function queueOne(id:string){await requestPriceRefresh([id]);setItems(await getInventory());setNote("Price refresh requested. Ask ChatGPT: ‘Refresh my BrickAlpha prices.’")}
 async function queueAll(){setBusy(true);try{await requestPriceRefresh();setItems(await getInventory());setNote("All inventory prices are queued. Ask ChatGPT: ‘Refresh my BrickAlpha prices.’")}finally{setBusy(false)}}
 return <><div className="header"><div><div className="eyebrow">Supabase collection database</div><h1>Inventory</h1><div className="muted">Your collection is now centrally stored so ChatGPT can research and update market values.</div></div><div className="actions"><button className="btn secondary" onClick={queueAll} disabled={busy}>Queue all price refreshes</button><button className="btn accent" onClick={openAdd}>+ Add Set</button></div></div>
 <div className="notice" style={{marginBottom:14}}>{note}{queued>0?` · ${queued} set${queued===1?"":"s"} waiting for ChatGPT price research.`:""}</div>
 <div className="toolbar"><input className="input" placeholder="Search set, number or theme…" value={q} onChange={e=>setQ(e.target.value)}/></div>
 <div className="table-wrap"><table><thead><tr><th>Set</th><th>Condition</th><th>Qty</th><th>Your cost</th><th>Market</th><th>Store price</th><th>Position value</th><th>Price status</th><th></th></tr></thead><tbody>{filtered.map(i=><tr key={i.id}><td><div className="setcell"><div className="thumb">{i.imageUrl?<img src={i.imageUrl} alt=""/>:"LEGO"}</div><div><b>{i.name}</b><div className="muted">#{i.setNumber} · {i.theme}</div></div></div></td><td>{i.condition}</td><td>{i.quantity}</td><td>{money(i.cost)}</td><td><b>{money(i.market)}</b>{i.marketSources?.length?<div className="muted">{i.marketSources.length} researched sources</div>:null}</td><td>{money(i.storePrice)}</td><td><b>{money(i.market*i.quantity)}</b></td><td>{i.refreshRequested?<span className="pill amber">Queued</span>:<span className="pill green">Current</span>}<div className="muted">{i.lastUpdated?new Date(i.lastUpdated).toLocaleDateString():"Never researched"}</div></td><td><div className="actions"><button className="btn secondary" onClick={()=>queueOne(i.id)}>Refresh price</button><button className="btn secondary" onClick={()=>openEdit(i)}>Edit</button><button className="btn secondary danger" onClick={()=>remove(i.id)}>Delete</button></div></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">No sets found.</div>}</div>
 {open&&<div className="modal-back"><div className="modal"><div className="section-title"><h2>{editing?"Edit LEGO set":"Add LEGO set"}</h2><button className="btn secondary" onClick={()=>setOpen(false)}>Close</button></div><div className="form-grid"><div className="field"><label>Set number</label><div className="actions"><input value={form.setNumber} onChange={e=>setForm({...form,setNumber:e.target.value})}/><button className="btn secondary" onClick={lookupSet}>Auto fill</button></div></div><div className="field"><label>Set name</label><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>Theme</label><input value={form.theme} onChange={e=>setForm({...form,theme:e.target.value})}/></div><div className="field"><label>Condition</label><select value={form.condition} onChange={e=>setForm({...form,condition:e.target.value as Condition})}><option>New/Sealed</option><option>Used Complete</option><option>Used Incomplete</option></select></div><div className="field"><label>Quantity</label><input type="number" min="1" value={form.quantity} onChange={e=>setForm({...form,quantity:Number(e.target.value)})}/></div><div className="field"><label>Your cost / unit</label><input type="number" step="0.01" value={form.cost} onChange={e=>setForm({...form,cost:Number(e.target.value)})}/></div><div className="field"><label>Current market value / unit</label><input type="number" step="0.01" value={form.market} onChange={e=>setForm({...form,market:Number(e.target.value)})}/><small className="muted">ChatGPT research can update this automatically in Supabase.</small></div><div className="field"><label>Your store price / unit</label><input type="number" step="0.01" value={form.storePrice} onChange={e=>setForm({...form,storePrice:Number(e.target.value)})}/></div><div className="field"><label>Status</label><select value={form.status} onChange={e=>setForm({...form,status:e.target.value as InventoryStatus})}><option>For Sale</option><option>Hold</option><option>Personal</option><option>Consignment</option></select></div><div className="field"><label>Location</label><input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></div><div className="field full"><label>Notes</label><textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div></div><div className="actions footer-actions"><button className="btn secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn accent" onClick={save} disabled={busy}>{busy?"Saving…":editing?"Save changes":"Add to inventory"}</button></div></div></div>}</>;
}
